### ISSUE TITLE
Log cluttered by `CoercionError`s

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/y-video-back-end#119]
The log is full of `CoercionError`s like this one:

```
2022-09-09 12:03:41,874 [XNIO-1 task-23] ERROR y-video-back.middleware.exception - Request coercion failed: #reitit.coercion.CoercionError{:spec #Spec{:form (clojure.spec.alpha/keys :req-un [:spec$233/session-id]), :type :map, :leaf? false}, :problems {:clojure.spec.alpha/problems ({:path [:session-id], :pred clojure.core/uuid?, :val "", :via [:spec$233/session-id], :in [:session-id]}), :clojure.spec.alpha/spec #Spec{:form (clojure.spec.alpha/keys :req-un [:spec$233/session-id]), :type :map, :leaf? false}, :clojure.spec.alpha/value {:session-id ""}}}
clojure.lang.ExceptionInfo: Request coercion failed: #reitit.coercion.CoercionError{:spec #Spec{:form (clojure.spec.alpha/keys :req-un [:spec$233/session-id]), :type :map, :leaf? false}, :problems {:clojure.spec.alpha/problems ({:path [:session-id], :pred clojure.core/uuid?, :val "", :via [:spec$233/session-id], :in [:session-id]}), :clojure.spec.alpha/spec #Spec{:form (clojure.spec.alpha/keys :req-un [:spec$233/session-id]), :type :map, :leaf? false}, :clojure.spec.alpha/value {:session-id ""}}}
        at reitit.coercion$request_coercion_failed_BANG_.invokeStatic(coercion.cljc:46) ~[y-video-back-end.jar:na]
        at reitit.coercion$request_coercion_failed_BANG_.invoke(coercion.cljc:44) ~[y-video-back-end.jar:na]
        at reitit.coercion$request_coercer$fn__26568.invoke(coercion.cljc:86) ~[y-video-back-end.jar:na]
        at reitit.coercion$coerce_request$fn__26580.invoke(coercion.cljc:113) ~[y-video-back-end.jar:na]
        at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:377) ~[y-video-back-end.jar:na]
        at clojure.core$fn__8437.invokeStatic(core.clj:6845) ~[y-video-back-end.jar:na]
        at clojure.core$fn__8437.invoke(core.clj:6830) ~[y-video-back-end.jar:na]
        at clojure.core.protocols$fn__8167$G__8162__8176.invoke(protocols.clj:175) ~[y-video-back-end.jar:na]
        at clojure.core$reduce_kv.invokeStatic(core.clj:6856) ~[y-video-back-end.jar:na]
        at clojure.core$reduce_kv.invoke(core.clj:6847) ~[y-video-back-end.jar:na]
        at reitit.coercion$coerce_request.invokeStatic(coercion.cljc:111) ~[y-video-back-end.jar:na]
        at reitit.coercion$coerce_request.invoke(coercion.cljc:110) ~[y-video-back-end.jar:na]
        at reitit.ring.coercion$fn__28599$fn__28601$fn__28602.invoke(coercion.cljc:39) ~[y-video-back-end.jar:na]
        at reitit.ring.coercion$fn__28608$fn__28610$fn__28611.invoke(coercion.cljc:63) ~[y-video-back-end.jar:na]
        at muuntaja.middleware$wrap_format_request$fn__30119.invoke(middleware.clj:114) ~[y-video-back-end.jar:na]
        at reitit.ring.middleware.exception$wrap$fn__31068$fn__31069.invoke(exception.clj:49) ~[y-video-back-end.jar:na]
        at muuntaja.middleware$wrap_format_response$fn__30123.invoke(middleware.clj:132) [y-video-back-end.jar:na]
        at muuntaja.middleware$wrap_format_negotiate$fn__30116.invoke(middleware.clj:96) [y-video-back-end.jar:na]
        at ring.middleware.params$wrap_params$fn__30180.invoke(params.clj:67) [y-video-back-end.jar:na]
        at ring.middleware.cors$wrap_cors$fn__34397.invoke(cors.clj:157) [y-video-back-end.jar:na]
        at reitit.ring$ring_handler$fn__28351.invoke(ring.cljc:292) [y-video-back-end.jar:na]
        at clojure.lang.AFn.applyToHelper(AFn.java:154) [y-video-back-end.jar:na]
        at clojure.lang.AFn.applyTo(AFn.java:144) [y-video-back-end.jar:na]
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) [y-video-back-end.jar:na]
        at clojure.lang.RestFn.invoke(RestFn.java:408) [y-video-back-end.jar:na]
        at clojure.lang.Var.invoke(Var.java:384) [y-video-back-end.jar:na]
        at immutant.web.internal.undertow$create_http_handler$reify__36310.handleRequest(undertow.clj:239) [y-video-back-end.jar:na]
        at org.projectodd.wunderboss.web.undertow.async.websocket.UndertowWebsocket$2.handleRequest(UndertowWebsocket.java:109) [y-video-back-end.jar:na]
        at io.undertow.server.session.SessionAttachmentHandler.handleRequest(SessionAttachmentHandler.java:68) [y-video-back-end.jar:na]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211) [y-video-back-end.jar:na]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [y-video-back-end.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_342]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_342]
        at java.lang.Thread.run(Thread.java:750) [na:1.8.0_342]
```

**Comment by reynoldsnlp** [comment]
@WorldsEndless this isn't urgent, but it would be nice to have fixed, and I'm guessing it's as simple as a `try`-`except`.

**Comment by reynoldsnlp** [comment]
This could be nice to fix at the same time as #121 since it appears that these errors are coming up with `session-id`s.

**Comment by reynoldsnlp** [comment]
I found this very old message from Matthew in the [Developers Manual](https://github.com/BYU-ODH/y-video-back-end/blob/development/developers_manual.md) he wrote for this project:

> When a browser first loads Y-Video, it makes a call to [https://yvideo.byu.edu/api/user](https://yvideo.byu.edu/api/docs/index.html#!/user/get_api_user). If the user is not logged in, then the request lacks a session-id and the browser gets a 400 error, which prompts it to show the public landing page. While this works, it fills the log files on the back end with request coercion errors. We need to coordinate an error-free method with the front end team for checking if a user is logged in or not. The back end currently supplies a boolean called :logged-in when rendering the index page. The front end could use this.
