### ISSUE TITLE
When `last-verified` is `nil`, `is-valid-access-time` chokes

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/y-video-back-end#146]
2023-07-28 12:41:07,610 [XNIO-1 task-106] ERROR y-video-back.middleware.exception - No implementation of method: :inst-ms* of protocol: #'clojure.core/Inst found for class: nil
java.lang.IllegalArgumentException: No implementation of method: :inst-ms* of protocol: #'clojure.core/Inst found for class: nil
        at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583) ~[y-video-back-end.jar:na]
        at clojure.core$fn__8399$G__8394__8404.invoke(core.clj:6780) ~[y-video-back-end.jar:na]
        at clojure.core$inst_ms.invokeStatic(core.clj:6791) ~[y-video-back-end.jar:na]
        at clojure.core$inst_ms.invoke(core.clj:6787) ~[y-video-back-end.jar:na]
        at y_video_back.routes.service_handlers.utils.utils$is_valid_access_time.invokeStatic(utils.clj:57) ~[y-video-back-end.jar:na]
        at y_video_back.routes.service_handlers.utils.utils$is_valid_access_time.invoke(utils.clj:54) ~[y-video-back-end.jar:na]
        at y_video_back.routes.service_handlers.handlers.collection_methods$collection_get_all_contents$fn__33461.invoke(collection_methods.clj:168) ~[y-video-back-end.jar:na]
        at clojure.core$filter$fn__5893.invoke(core.clj:2821) ~[y-video-back-end.jar:na]
        at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[y-video-back-end.jar:na]
        at clojure.lang.LazySeq.seq(LazySeq.java:51) ~[y-video-back-end.jar:na]
        at clojure.lang.Cons.next(Cons.java:39) ~[y-video-back-end.jar:na]
        at clojure.lang.RT.next(RT.java:713) ~[y-video-back-end.jar:na]
        at clojure.core$next__5386.invokeStatic(core.clj:64) ~[y-video-back-end.jar:na]
        at clojure.core$dorun.invokeStatic(core.clj:3142) ~[y-video-back-end.jar:na]
        at clojure.core$doall.invokeStatic(core.clj:3148) ~[y-video-back-end.jar:na]
        at clojure.core$doall.invoke(core.clj:3148) ~[y-video-back-end.jar:na]
        at y_video_back.routes.service_handlers.handlers.collection_methods$collection_get_all_contents.invokeStatic(collection_methods.clj:167) ~[y-video-back-end.jar:na]
        at y_video_back.routes.service_handlers.handlers.collection_methods$collection_get_all_contents.invoke(collection_methods.clj:161) ~[y-video-back-end.jar:na]
        at y_video_back.routes.service_handlers.handlers.collection_handlers$fn__33757.invokeStatic(collection_handlers.clj:185) ~[y-video-back-end.jar:na]
        at y_video_back.routes.service_handlers.handlers.collection_handlers$fn__33757.invoke(collection_handlers.clj:182) ~[y-video-back-end.jar:na]
        at y_video_back.middleware$log_endpoint_access$fn__28978.invoke(middleware.clj:231) ~[y-video-back-end.jar:na]
        at y_video_back.middleware$add_id_and_username$fn__28951.invoke(middleware.clj:171) ~[y-video-back-end.jar:na]
        at y_video_back.middleware$check_permission$fn__28954.invoke(middleware.clj:197) ~[y-video-back-end.jar:na]
        at y_video_back.middleware$add_session_id$fn__28967.invoke(middleware.clj:214) ~[y-video-back-end.jar:na]
        at ring.middleware.multipart_params$wrap_multipart_params$fn__18676.invoke(multipart_params.clj:173) ~[y-video-back-end.jar:na]
        at reitit.ring.coercion$fn__30973$fn__30975$fn__30976.invoke(coercion.cljc:40) ~[y-video-back-end.jar:na]
        at reitit.ring.coercion$fn__30982$fn__30984$fn__30985.invoke(coercion.cljc:63) ~[y-video-back-end.jar:na]
        at muuntaja.middleware$wrap_format_request$fn__32421.invoke(middleware.clj:114) ~[y-video-back-end.jar:na]
        at reitit.ring.middleware.exception$wrap$fn__33371$fn__33372.invoke(exception.clj:49) ~[y-video-back-end.jar:na]
        at muuntaja.middleware$wrap_format_response$fn__32425.invoke(middleware.clj:132) ~[y-video-back-end.jar:na]
        at muuntaja.middleware$wrap_format_negotiate$fn__32418.invoke(middleware.clj:96) ~[y-video-back-end.jar:na]
        at ring.middleware.params$wrap_params$fn__18692.invoke(params.clj:67) ~[y-video-back-end.jar:na]
        at ring.middleware.cors$wrap_cors$fn__19980.invoke(cors.clj:157) ~[y-video-back-end.jar:na]
        at reitit.ring$ring_handler$fn__30820.invoke(ring.cljc:292) ~[y-video-back-end.jar:na]
        at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[y-video-back-end.jar:na]
        at clojure.lang.AFn.applyTo(AFn.java:144) ~[y-video-back-end.jar:na]
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[y-video-back-end.jar:na]
        at clojure.lang.RestFn.invoke(RestFn.java:408) ~[y-video-back-end.jar:na]
        at clojure.lang.Var.invoke(Var.java:384) ~[y-video-back-end.jar:na]
        at immutant.web.internal.undertow$create_http_handler$reify__34765.handleRequest(undertow.clj:239) ~[y-video-back-end.jar:na]
        at org.projectodd.wunderboss.web.undertow.async.websocket.UndertowWebsocket$2.handleRequest(UndertowWebsocket.java:109) ~[y-video-back-end.jar:na]
        at io.undertow.server.session.SessionAttachmentHandler.handleRequest(SessionAttachmentHandler.java:68) ~[y-video-back-end.jar:na]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211) ~[y-video-back-end.jar:na]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) ~[y-video-back-end.jar:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

**Comment by reynoldsnlp** [comment]
Can test with collection id `61889ee9-aadb-48cb-971e-03087f45aeec`
